### ISSUE TITLE
idapython error use 'idat64.exe -A -smain.py'

### ISSUE THREAD

**Issue by xunge** [NyaMisty/docker-wine-ida#10]
I want to use idapython to perform batch background execution of scripts. The execution command is as follows:
`docker exec -it docker-ida wine /root/.wine/drive_c/IDA/idat64.exe -A -L/root/log.txt -s/root/ida_asm.py /root/bin`

but it reports an error as follows:
```
Loading processor module C:\IDA\procs\arm64.dll for ARM...Initializing processor module ARM...OK
Loading type libraries...
Autoanalysis subsystem has been initialized.
C:\Program Files\Python39\lib\site-packages\qtpy\__init__.py:289: PythonQtWarning: Qt5 version 5.6.3 is not supported by QtPy. To ensure your application works correctly with QtPy, please upgrade to Qt5 5.9.0 or later.
  warnings.warn(warning_message, PythonQtWarning)
Exception ignored in: <function BaseEventLoop.__del__ at 0x000000000D605550>
Traceback (most recent call last):
  File "C:\Program Files\Python39\Lib\asyncio\base_events.py", line 680, in __del__
    if not self.is_closed():
  File "C:\Program Files\Python39\Lib\asyncio\base_events.py", line 677, in is_closed
    return self._closed
AttributeError: 'QIOCPEventLoop' object has no attribute '_closed'
C:\IDA\plugins\ipyida_plugin_stub.py: No QApplication has been instantiated
Traceback (most recent call last):
  File "C:\IDA\python\3\ida_idaapi.py", line 616, in IDAPython_ExecScript
    exec(code, g)
  File "C:/IDA/plugins/ipyida_plugin_stub.py", line 11, in <module>
    from ipyida.ida_plugin import PLUGIN_ENTRY, IPyIDAPlugIn
  File "C:\Program Files\Python39\lib\site-packages\ipyida\ida_plugin.py", line 62, in <module>
    _setup_asyncio_event_loop()
  File "C:\Program Files\Python39\lib\site-packages\ipyida\ida_plugin.py", line 58, in _setup_asyncio_event_loop
    loop = qasync.QEventLoop(qapp, already_running=True)
  File "C:\Program Files\Python39\lib\site-packages\qasync\__init__.py", line 336, in __init__
    assert self.__app is not None, "No QApplication has been instantiated"
AssertionError: No QApplication has been instantiated

Unknown switch '-s' -> OK
Unloading IDP module C:\IDA\procs\arm64.dll...
```
However, idapython scripts can be executed normally in the UI interface.
Can you tell me why? Thank you

**Comment by NyaMisty** [comment]
That's intended. idat doesn't have QT framework, so you can't load my IPyIDA plug-in into it.
you can choose to delete ipyida related stuffs in plugins folder, or directly use ida/ida64 instead.
